services:
  chores-eink-display-simulator:
    build: .
    volumes:
      - .:/home
    environment:
      CHORES_API_URL: ${CHORES_API_URL:-http://host.docker.internal:8080}
      RESOURCES_PATH: ${RESOURCES_PATH:-/home/resources}
      REFRESH_HOUR: ${REFRESH_HOUR:-5}
